# Generated by Django 2.2.4 on 2019-08-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leap_year', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leapyear',
            name='year',
            field=models.IntegerField(),
        ),
    ]
